stages:
  - build
  - deploy

# 빌드 단계
build:
  stage: build
  script:
    - echo "Installing dependencies"
    - npm install
    - echo "Building the project"
    - npm run build
  artifacts:
    paths:
      - dist/ # 빌드 결과물 폴더
    expire_in: 1 hour # 아티팩트 보존 시간 설정
  only:
    - main
    - build
  tags:
    - frontend

# 배포 단계
deploy:
  stage: deploy
  script:
    - echo "Starting deployment"
    # 빌드 결과물 전송
    - scp -r dist/ kdt@34.64.75.50:~/frontend/auraSphere/dist
    # 원격 서버에서 빌드 결과물로 배포 준비
    # - ssh kdt@34.64.75.50 " cd ~/frontend/auraSphere && npm install && pm2 restart app "
  dependencies:
    - build # build 단계의 아티팩트를 가져옵니다
  only:
    - main # main 브랜치에 코드가 머지될 때만 실행
  tags:
    - frontend
  environment:
    name: production
    url: http://34.64.75.50
